"""add factures table

Revision ID: 7cc1ce90459a
Revises: 489b3b246c55
Create Date: 2026-07-21 12:16:16.217386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc1ce90459a'
down_revision: Union[str, Sequence[str], None] = '489b3b246c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(length=255), nullable=True),
    sa.Column('nom_fichier', sa.String(length=500), nullable=True),
    sa.Column('taille_octets', sa.Integer(), nullable=True),
    sa.Column('date_import', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_nom', sa.String(length=255), nullable=True),
    sa.Column('client_email', sa.String(length=255), nullable=True),
    sa.Column('montant_ht', sa.Float(), nullable=True),
    sa.Column('taux_tva', sa.Float(), nullable=True),
    sa.Column('montant_ttc', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date_facture', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'numero', name='uq_facture_user_numero')
    )
    op.create_index(op.f('ix_factures_user_id'), 'factures', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_factures_user_id'), table_name='factures')
    op.drop_table('factures')
    # ### end Alembic commands ###
